### PR TITLE
Fix #260: Add gettext functions to all messages

### LINKED ISSUE #260: Multiple not translated strings
I'd like to have my docs translated to Polish and now I have to translate displayed strings myself. Examples from current master:

https://github.com/snide/sphinx_rtd_theme/blob/012d42db6a2b00f799223963fb8b0aa3754630eb/sphinx_rtd_theme/breadcrumbs.html
"Docs", "Edit on GitHub", "Edit on Bitbucket", "View page source"

I expected the template to honor 'language' setting from the configuration file.

### PR DESCRIPTION
**Pull request by Mingun**
This pull request added missing `gettext` tags to messages, which should be translatable. Partially closes #260.

### CODE REVIEW

**Comment by ericholscher** [comment]
Seems like a good addition. @agjohnson any thoughts?

**Comment by agjohnson** [comment]
We shouldn't translate ``Read the Docs``, as it's branding, not just a string. Looks good otherwise.

**Comment by Mingun** [comment]
> We shouldn't translate  `Read the Docs`, as it's branding, not just a string.

Yes, I known. But this still UI string and in some cases may be useful to «translate» it. Furhermore, the presence feature better its absence.

**Comment by agjohnson** [comment]
I would argue we *never* want to translate it. It's not just UI text, it's our brand, name of the site, and our domain name -- none of which transfers to other languages cleanly.

**Comment by mitya57** [comment]
I think it can be closed now that #343 is merged?

**Comment by Mingun** [comment]
Closing, because same PR #343 was already merged.

**Pull request closed without merging**
