### PR TITLE
Drop dependency on Sphinx

### LINKED ISSUE #189: Relaxing sphinx requirement
I know this may come across as a strange request, but is there a way of relaxing and/or removing the sphinx requirement. This is causing some of us build trouble with sphinx ( https://github.com/sphinx-doc/sphinx/issues/1845 ).

### PR DESCRIPTION
**Pull request by mitya57**
As suggested by @birkenfeld in #189, this is the easiest way to solve the dependency loop that is creating problems for packagers. Fixes #189.

### CODE REVIEW

**Comment by ericholscher** [comment]
Thanks!

**Comment by jakirkham** [comment]
Thanks guys. And this just works for you without doing anything else?

**Comment by mitya57** [comment]
@ericholscher: Thanks for merging it!

@jakirkham: It works for us in Debian (we have been shipping this patch for quite some time now), though I don't quite understand what your question is about.

**Comment by jakirkham** [comment]
@mitya57, ok, I was just asking because I didn't know if there were imports that needed to be changed or other things. However, it doesn't look like `sphinx` was being imported anywhere.

**Comment by mitya57** [comment]
Right, sphinx is not imported anywhere.

**Pull request merged**
