### PR TITLE
Add support for l3+l4 nav menus in theme, alter scrolling

### LINKED ISSUE #25: Add click to open submenu functionality
Thinking of adding a right aligned down caret for the secondary ability of opening a subtree in the menu.

### LINKED ISSUE #76: Show 3rd level headers
Copying from https://github.com/rtfd/readthedocs.org/issues/604

The new theme is lovely, but the way it handles the sidebar navigation breaks things.

http://python-notes.curiousefficiency.org/en/latest/python3/questions_and_answers.html is a good example of the problem.

With the default Sphinx approach, navigation within that page is easy: the level 2 heading and the level 3 subheadings are shown at the top of the side nav bar, with the previous and next topics presented below that.

With the new default RTFD theme, the side bar always shows the nav for the entire site, bringing in all the other irrelevant L1 headings, but doesn't display any of the L3 headings within the document itself. That means I can only navigate within the doc by popping back up to the overview page for that section to get access to the third level of the TOC.

### PR DESCRIPTION
**Pull request by agjohnson**
Adds l3 + l4 nav menus, with more intuitive scrolling to make wandering the
additional nav menu items much easier. Resolves #25. Resolves #76.

* Reuses some styles for l3 + l4 navs items
* Nav interaction was changed to be more intuitive:
  * Nav is always sticky, doesn't scroll past end of content
  * Nav scrolls up immediately on window scroll events
  * Nav scrolls independently
  * Adds TOC expand plus links to the left of nav elements with children, these
    are added and update dynamically
  * Links in nav don't automatically scroll nav
  * Scrolling content will start scrolling nav again
  * Adds URL fragment handling to link and show current anchor links

screen shot 2015-05-04 at 2 39 50 pm

### CODE REVIEW

**Comment by beddari** [comment]
Thank you very much :+1:

**Comment by jturner314** [comment]
This looks great and is a significant improvement. The only issue I see is the handling of a top-level toctree with the `:titlesonly:` option. Here's an example where the top-level toctree uses the `:titlesonly:` option and the "My Designs" page has sections not shown in the sidebar:

temp

Note the `[-]` beside "My Designs" even though there are no visible sections underneath it. The theme should either show the sections in the sidebar or hide the `[-]`.

**Comment by agjohnson** [comment]
@jturner314 good catch, seems there are some edge cases that need to be addressed. feel free to open a ticket against this, i'll hopefully address a few of these issues this week

**Comment by jturner314** [comment]
Okay, I just created #196. Thanks for adding these additional-depth menus. They look great, and the 2-level limitation has been bothering me for a while. :+1:

**Pull request merged**
