### PR TITLE
Cast maxdepth to an int.

### LINKED ISSUE #334: Maxdepth is a int, not a string.
https://github.com/snide/sphinx_rtd_theme/pull/309 seem to have make maxdepth a string ('4')  which make sphinx complain in python 3  that string and int are not-orderable.

### PR DESCRIPTION
**Pull request by Carreau**
closes #334

### CODE REVIEW

**Comment by Carreau** [comment]
I'm not sure how to do it differently. I looked at several other sphinx
theme to figure out how they were having default value that were integers.
That's the only way I found. I agree that I would prefer doing it through
an explicit python API but as far as I can tell, we need to patch Sphinx
for that.

**Comment by Carreau** [comment]
Get we get that in to fix the theme ? Otherwise it is plainly broken for some projects.

Thanks !

**Comment by ericholscher** [comment]
Looks good to me. We can try and fix this another way over time if need be.

**Comment by Carreau** [comment]
Thanks, appreciate it.

**Pull request merged**
