### PR TITLE
Fixed width in higher resolutions

### PR DESCRIPTION
**Pull request by rougin**
This is my fix to issue https://github.com/snide/sphinx_rtd_theme/issues/207.

### CODE REVIEW

**Comment by ericholscher** [comment]
This was a specific design decision not to let the page width expand. It makes text harder to read as the lines get longer. If you want something that will actually fix this, at large resolutions we should likely increase the font size or something to make sure that the text line-width's stay the same proportion, not just allow the page to grow larger.

**Comment by ericholscher** [comment]
More info: http://baymard.com/blog/line-length-readability

**Comment by agjohnson** [comment]
Also -1 on making the content width expand, I agree the fix to this is expanding font size. High resolution displays could easily set a higher font size on `body` via media queries.

Closing this PR, feel free to submit another PR with the font size changes above.

**Comment by rougin** [comment]
Thanks for this! I'll try to submit another PR for this next time.

**Pull request closed without merging**
