### PR TITLE
Use 100% width for rst-footer-buttons

### PR DESCRIPTION
**Pull request by Blendify**
This fixes the buttons from jumping around on small pages/ resizing

### CODE REVIEW

**Comment by ericholscher** [comment]
Is there an example that this fixes? Would be good to understand a bit more.

**Comment by Blendify** [comment]
broken page

Here is an example

**Comment by Blendify** [comment]
To fix this we did:

```
.rst-footer-buttons::before , .rst-footer-buttons::after{
	width: 100%;
}
```
I assume this does the same thing; just started using sass today.

**Comment by Blendify** [comment]
planing changes here

**Comment by ericholscher** [comment]
Seems like a reasonable fix, thanks. I'll take a look and merge it next week.

**Comment by Blendify** [comment]
See https://github.com/snide/sphinx_rtd_theme/pull/370

**Pull request closed without merging**
